export interface Resource {
  id: string;
  name: string;
  type: "政府服務" | "民間機構" | "支持團體" | "法律資源" | "教育資源";
  description: string;
  phone?: string;
  url?: string;
  cities: string[];
  cmsEligibility: number[];
  tags: string[];
}

export const RESOURCE_TYPES = ["政府服務", "民間機構", "支持團體", "法律資源", "教育資源"] as const;

export const CITIES = [
  "全國", "台北市", "新北市", "桃園市", "台中市", "台南市", "高雄市",
  "基隆市", "新竹市", "新竹縣", "苗栗縣", "彰化縣", "南投縣", "雲林縣",
  "嘉義市", "嘉義縣", "屏東縣", "宜蘭縣", "花蓮縣", "台東縣",
  "澎湖縣", "金門縣", "連江縣",
];

export const RESOURCES: Resource[] = [
  {
    id: "1966",
    name: "長照專線 1966",
    type: "政府服務",
    description: "衛福部長照服務免費諮詢專線，提供長照資源媒合、補助申請諮詢，由照顧管理專員一對一服務。每日 8:00~20:00。",
    phone: "1966",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["補助申請", "資源媒合", "免費諮詢", "24小時"],
  },
  {
    id: "aca-care",
    name: "各縣市照顧管理中心",
    type: "政府服務",
    description: "辦理 CMS 失能評估、長照服務申請、個案管理，是申請所有長照服務的第一站。各縣市均設有辦事處。",
    phone: "1966（轉介）",
    cities: ["全國"],
    cmsEligibility: [2, 3, 4, 5, 6, 7, 8],
    tags: ["CMS評估", "長照申請", "個案管理"],
  },
  {
    id: "respite",
    name: "喘息服務申請",
    type: "政府服務",
    description: "讓主要照顧者獲得短暫休息的服務，包含居家喘息（替代照顧）與機構喘息（短期住宿）。每年有補助額度。",
    phone: "1966",
    cities: ["全國"],
    cmsEligibility: [2, 3, 4, 5, 6, 7, 8],
    tags: ["照顧者支持", "短期住宿", "居家替代"],
  },
  {
    id: "disability-cert",
    name: "身心障礙鑑定申請",
    type: "政府服務",
    description: "領有身心障礙證明可享有多項福利（交通、稅務、醫療費用減免）。向戶籍地衛生局申請鑑定。",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["身障補助", "鑑定申請", "稅務減免"],
  },
  {
    id: "taipei-longcare",
    name: "台北市長照資源中心",
    type: "政府服務",
    description: "台北市提供的長照服務整合窗口，包含到宅評估、居家服務、日間照顧等完整服務鏈。",
    phone: "02-2728-7799",
    cities: ["台北市"],
    cmsEligibility: [2, 3, 4, 5, 6, 7, 8],
    tags: ["居家服務", "日間照顧", "到宅評估"],
  },
  {
    id: "nhia-care",
    name: "健保居家護理",
    type: "政府服務",
    description: "行動不便的長輩可申請健保居家護理，由護理師定期到府進行醫療照護，包含換藥、導尿管更換等。需有醫師開立醫囑。",
    cities: ["全國"],
    cmsEligibility: [3, 4, 5, 6, 7, 8],
    tags: ["居家護理", "健保給付", "醫療照護"],
  },
  {
    id: "atda",
    name: "台灣失智症協會",
    type: "民間機構",
    description: "提供失智症衛教資訊、照顧技巧課程、家屬支持服務，設有各縣市分會，辦理社區講座與家屬聯誼。",
    phone: "02-2598-8580",
    url: "https://www.tada2002.org.tw",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["失智症", "衛教資訊", "家屬課程"],
  },
  {
    id: "stroke-foundation",
    name: "台灣腦中風病友協會",
    type: "民間機構",
    description: "提供中風患者與家屬的復健資訊、照顧指導、病友互助活動，定期舉辦復健示範課程。",
    url: "http://stroke.org.tw",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["中風復健", "病友支持", "復健資訊"],
  },
  {
    id: "parkinsons-tw",
    name: "台灣動作障礙學會",
    type: "民間機構",
    description: "推廣帕金森氏症及相關動作障礙的醫療知識，提供病友衛教資料，舉辦全國病友大會。",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["帕金森", "動作障礙", "醫療資訊"],
  },
  {
    id: "eden-social",
    name: "伊甸社會福利基金會",
    type: "民間機構",
    description: "提供居家服務、日間照顧、輔具租借、照顧技巧培訓等多元長照服務，服務遍及全台。",
    phone: "02-2230-0292",
    url: "https://www.eden.org.tw",
    cities: ["全國"],
    cmsEligibility: [2, 3, 4, 5, 6, 7, 8],
    tags: ["居家服務", "輔具租借", "日間照顧"],
  },
  {
    id: "synlin",
    name: "心路基金會",
    type: "民間機構",
    description: "提供身心障礙者與長者的日間照顧、居家服務、社區融合服務，在台北及新北市有多個服務據點。",
    phone: "02-2598-8108",
    cities: ["台北市", "新北市"],
    cmsEligibility: [2, 3, 4, 5, 6, 7, 8],
    tags: ["日間照顧", "社區服務", "身心障礙"],
  },
  {
    id: "caregiver-support-taipei",
    name: "台北市家庭照顧者關懷協會",
    type: "支持團體",
    description: "提供照顧者情緒支持、同儕互助團體、照顧技巧工作坊，讓主要照顧者不再孤軍奮戰。",
    phone: "02-2599-1350",
    cities: ["台北市"],
    cmsEligibility: [],
    tags: ["照顧者支持", "互助團體", "工作坊"],
  },
  {
    id: "family-caregiver-tw",
    name: "台灣家庭照顧者關懷總會",
    type: "支持團體",
    description: "全國最大的照顧者支持組織，提供電話諮詢、支持團體、照顧技巧培訓，設有全國服務據點。",
    phone: "0800-580-097（免費）",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["照顧者支持", "免費諮詢", "全國服務"],
  },
  {
    id: "dementia-support-group",
    name: "失智家屬支持團體",
    type: "支持團體",
    description: "由失智症協會各地辦理，讓照顧失智症長輩的家屬互相交流、分享經驗，獲得情緒支持與實用建議。",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["失智家屬", "情緒支持", "經驗交流"],
  },
  {
    id: "counseling-1925",
    name: "安心專線 1925",
    type: "支持團體",
    description: "衛福部心理健康諮詢專線，24 小時服務，適合照顧者在壓力過大、情緒崩潰時尋求即時的心理支持。",
    phone: "1925",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["心理支持", "24小時", "情緒危機"],
  },
  {
    id: "laf",
    name: "法律扶助基金會",
    type: "法律資源",
    description: "提供低收入及弱勢族群免費法律諮詢，包含監護宣告、遺產繼承、財產糾紛等，各縣市均有分會。",
    phone: "412-8518（免市話費）",
    url: "https://www.laf.org.tw",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["免費諮詢", "監護宣告", "遺產繼承"],
  },
  {
    id: "notary",
    name: "民間公證人協會",
    type: "法律資源",
    description: "辦理公證遺囑、安養信託公證等法律文件認證，確保法律效力，費用依項目而定。",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["遺囑公證", "安養信託", "法律文件"],
  },
  {
    id: "court-family",
    name: "各地方法院家事服務中心",
    type: "法律資源",
    description: "辦理監護宣告、輔助宣告聲請，提供免費法律諮詢服務，可向戶籍地法院提出申請。",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["監護宣告", "法院申請", "免費諮詢"],
  },
  {
    id: "nhia-edu",
    name: "健保署長照相關衛教",
    type: "教育資源",
    description: "健保署提供的長期照護衛教資料，包含長照服務說明、補助計算教學影片、申請流程圖解。",
    url: "https://www.nhi.gov.tw",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["衛教資料", "申請教學", "影片"],
  },
  {
    id: "mhlw-longcare-guide",
    name: "衛福部長照服務網",
    type: "教育資源",
    description: "衛福部官方長照資訊平台，提供最新補助政策、服務機構查詢、照顧知識庫，定期更新。",
    url: "https://1966.gov.tw",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["官方資訊", "政策公告", "機構查詢"],
  },
  {
    id: "caregiver-edu",
    name: "照顧技巧線上課程",
    type: "教育資源",
    description: "衛福部提供免費線上課程，內容涵蓋移位技巧、口腔護理、管路照護、失智症照顧等實用技能。",
    cities: ["全國"],
    cmsEligibility: [],
    tags: ["照顧技巧", "免費課程", "線上學習"],
  },
  {
    id: "kaohsiung-daytime",
    name: "高雄市日間照顧中心",
    type: "政府服務",
    description: "高雄市提供多處日間照顧中心，提供白天照顧、復健活動、餐食服務，晚上長輩可回家。",
    phone: "07-336-8333",
    cities: ["高雄市"],
    cmsEligibility: [2, 3, 4, 5, 6],
    tags: ["日間照顧", "復健活動", "餐食"],
  },
  {
    id: "taichung-home",
    name: "台中市居家服務中心",
    type: "政府服務",
    description: "台中市長照局提供居家服務派遣，包含身體照顧、家事協助、陪同就醫，申請通過可享政府補助。",
    phone: "04-2228-9111",
    cities: ["台中市"],
    cmsEligibility: [2, 3, 4, 5, 6, 7, 8],
    tags: ["居家服務", "身體照顧", "政府補助"],
  },
  {
    id: "assistive-device",
    name: "輔具資源中心",
    type: "政府服務",
    description: "各縣市輔具中心提供輔具評估、申請補助、租借服務，包含輪椅、助行器、移位機、氣墊床等。",
    phone: "1966（轉介）",
    cities: ["全國"],
    cmsEligibility: [2, 3, 4, 5, 6, 7, 8],
    tags: ["輔具租借", "輔具補助", "居家改造"],
  },
];
